/* Generated By:JavaCC: Do not edit this line. CCNeonParserConstants.java */
package org.netbeans.modules.php.nette.languages.neon;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CCNeonParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int KEYWORD = 2;
  /** RegularExpression Id. */
  int EXTENDS = 3;
  /** RegularExpression Id. */
  int COLON = 4;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int DASH = 6;
  /** RegularExpression Id. */
  int EQUALS = 7;
  /** RegularExpression Id. */
  int ASSIGN = 8;
  /** RegularExpression Id. */
  int LEFT_CURLY = 9;
  /** RegularExpression Id. */
  int RIGHT_CURLY = 10;
  /** RegularExpression Id. */
  int LEFT_SQUARED = 11;
  /** RegularExpression Id. */
  int RIGHT_SQUARED = 12;
  /** RegularExpression Id. */
  int COMMENT = 13;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int VARIABLE = 16;
  /** RegularExpression Id. */
  int LITERAL = 17;
  /** RegularExpression Id. */
  int EMPTY_LINE = 18;
  /** RegularExpression Id. */
  int SPACE = 19;
  /** RegularExpression Id. */
  int UNEXPECTED_CHAR = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "<KEYWORD>",
    "\"<\"",
    "\":\"",
    "\",\"",
    "\"-\"",
    "\"=\"",
    "\"=>\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<COMMENT>",
    "<STRING>",
    "<NUMBER>",
    "<VARIABLE>",
    "<LITERAL>",
    "<EMPTY_LINE>",
    "<SPACE>",
    "<UNEXPECTED_CHAR>",
  };

}
