package org.netbeans.modules.php.nette.options;

import org.openide.util.NbPreferences;

final class NettePanel extends javax.swing.JPanel {

	private final NetteOptionsPanelController controller;

	NettePanel(NetteOptionsPanelController controller) {
		this.controller = controller;
		initComponents();
		// TODO listen to changes in form fields and call controller.changed()
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        directoryChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        nettePathTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();

        directoryChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(NettePanel.class, "NettePanel.jLabel1.text")); // NOI18N

        nettePathTextField.setText(org.openide.util.NbBundle.getMessage(NettePanel.class, "NettePanel.nettePathTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(browseButton, org.openide.util.NbBundle.getMessage(NettePanel.class, "NettePanel.browseButton.text")); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nettePathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nettePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
		directoryChooser.showOpenDialog(this);

		nettePathTextField.setText(directoryChooser.getSelectedFile().toString());
	}//GEN-LAST:event_browseButtonActionPerformed

	void load() {
		// TODO read settings and initialize GUI
		// Example:
		// someCheckBox.setSelected(Preferences.userNodeForPackage(NettePanel.class).getBoolean("someFlag", false));
		// or for org.openide.util with API spec. version >= 7.4:
		// someCheckBox.setSelected(NbPreferences.forModule(NettePanel.class).getBoolean("someFlag", false));
		// or:
		// someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());

		nettePathTextField.setText(NbPreferences.forModule(NettePanel.class).get("nette-path", ""));
	}

	void store() {
		// TODO store modified settings
		// Example:
		// Preferences.userNodeForPackage(NettePanel.class).putBoolean("someFlag", someCheckBox.isSelected());
		// or for org.openide.util with API spec. version >= 7.4:
		// NbPreferences.forModule(NettePanel.class).putBoolean("someFlag", someCheckBox.isSelected());
		// or:
		// SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());

		NbPreferences.forModule(NettePanel.class).put("nette-path", nettePathTextField.getText());
	}

	boolean valid() {
		// TODO check whether form is consistent and complete
		return true;
	}
	    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JFileChooser directoryChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nettePathTextField;
    // End of variables declaration//GEN-END:variables
}
